
server:
  port: 8080
  context-path: /gtog  
spring:
  application:
     name: gtog
  http: 
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  boot:
    admin:
      url: http://localhost:1111
      username: admin
      password: secret      
    
# logging
logging:
  level:
    com:
      example:
        controller: INFO    

# mangement with spring boot actuator 
# works only with embedded tomcat   
management:
  security: 
    enabled: false
    
# actuator endpoints    
#endpoints:
#  info:
#    enabled: true
#  health:
#    enabled: true
#  metrics:
#    enabled: true

# info endpoint 
info:
  app:
    name: demo-app
    descritpion: This is just an demo assignment app
    version: 0.0.1-SNAPSHOT
